### ISSUE TITLE
Julia start-up slowness

### ISSUE THREAD

**Issue by shashi** [JunoLab/uber-juno#16]
It takes < 1 sec for me to start Julia, but evaluating `1` in atom takes more than 12 seconds.

Can anything in the way be sped up?

I am not sure where to open this issue... I'll just leave it here to remember.

**Comment by pfitzseb** [comment]
A way to mitigate that issue is to switch the `Boot Mode` to `Server` in the julia-client settings. That way you should always have "warmed up" julia instance ready to go instantenously (except on Atom start of course).

Some of the overhead is from importing the Julia side packages, some might be from JITing, but I don't think that accounts for all of it.

**Comment by shashi** [comment]
@pfitzseb thanks! that's helpful!

**Comment by shashi** [comment]
closing this in favor of https://github.com/JunoLab/atom-julia-client/issues/205
