### ISSUE TITLE
plotting with Gadfly doesn't work

### ISSUE THREAD

**Issue by RaananHadar** [JunoLab/uber-juno#26]
Hi,
Tried a simple:
```
using Gadfly
p = plot(x = rand(10), y = rand(10))
```
Plot does not appear in the plotting window. I tried using Pkg.checkout("Gadfly"), does not work.
I am using Julia 0.5 with a fresh install and all the latest versions of everything.

Thank you

**Comment by ptoche** [comment]
try ``Pkg.add("Gadfly")``  and/or ``Pkg.update()``

**Comment by MattFerraro** [comment]
Just verifying the problem here. Same setup as Raanan and seeing same behavior. Can't seem to get the plot to show up in any context. Command line executing a script doesn't work. REPL doesn't work. From within Atom with Juno doesn't work. Totally at a loss here.

**Comment by bjarthur** [comment]
your `plot` syntax is invalid as their is no `Geom` specifed.  this works for me:

```
plot(x = rand(10), y = rand(10), Geom.point)
```

**Comment by bjarthur** [comment]
hmmm, actually, i just learned that `Geom.point` is the default if none is specified, meaning your `plot` syntax is valid, contrary to my previous post.

your code snippet works for me as is, with atom 1.20.1, uber-juno 0.1.2, and Gadfly master.  as it's been seven months since your first post, can you test again?

**Comment by RaananHadar** [comment]
@bjarthur yes ofcourse. I will test again with the updated software and report back soon.
