### ISSUE TITLE
" 'where' could not be spawned" on Windows

### ISSUE THREAD

**Issue by Axure** [JunoLab/uber-juno#3]
> Juno: Installing Atom packages
> This will take a moment – hang tight!
> We'll let you know once it's done.
> 
> 'where' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
> 
> Error reporting uncaught exception Error: Cannot find module '../package.json'(…)(anonymous function) @ E:\Atom\resources\app.asar\node_modules\exception-reporting\lib\main.js:25
> events.js:141 Uncaught Error: spawn where ENOENT

Windows 10, Atom 1.8.0-beta3

**Comment by MikeInnes** [comment]
I've pushed a fix so that this issue won't come up again. This issue doesn't mean anything has gone badly wrong, just that Juno didn't find Julia – so you just need to set the Julia path in the julia-client settings, if you have already.

**Comment by pfitzseb** [comment]
You sure we didn't find julia in that case?
```js
> p = cp.spawn('where', ['julia']); p.on('exit', function(s){console.log(s)});
0

> p = cp.spawn('where', ['notjulia']); p.on('exit', function(s){console.log(s)});
1
```
I mean, sure, that commit fixes the immediate issue, but @Axure still seems to have `PATH` misconfigured if we can't spawn `where`. In theory, we could have a pop-up warning that says as much, but that may be a bit out of scope for us...

**Comment by MikeInnes** [comment]
Are you saying that the command output is reversed in Windows? If so I think that's a separate issue – although it's confusing that it doesn't reflect [this ref](https://technet.microsoft.com/en-us/library/cc753148(v=ws.11).aspx) (not that I checked that carefully when writing the code ;).

I'm open to other ways of checking the path than using `where` (Should we just do `julia --version`? Why don't we? (I think maybe I originally wanted to combine path-checking with command-checking.)). But I think the advice we give to users should be very straightforward regardless of the issue, i.e. just put the julia path in the settings.

**Comment by pfitzseb** [comment]
Nah, the code is correct -- we expect a `0` if `julia` is a valid command (`notjulia` isn't and returns a `1`).
Just wanted to illustrate that the error reported above doesn't stem from the fact that there's no `julia` command, but rather that there's no `where` (which should definitely be there if `C:/windows/system32` is on the path, as is the default on windows). And then a lot of other stuff is likely to go wrong as well, because having `.../system32` on the `path` is a valid assumption. But as I said, probably out of scope for us ;)

`julia --version` is a bit nicer imo, since then we don't have any other dependencies.

**Comment by MikeInnes** [comment]
Could we remove a bunch of code by just doing the check as `$path --version` for whatever path (/binary/alias) is given?
