### ISSUE TITLE
Removing the toolbar on disable/uninstall

### ISSUE THREAD

**Issue by daveh19** [JunoLab/uber-juno#5]
Hi,

I find it poor etiquette that when I disable or uninstall the uber-juno plugin that it doesn't remove its toolbar from the UI.

I'm not sure how the plugin manager in Atom handles dependencies upon uninstalls but ideally the toolbar addon should actually be removed if uber-juno is removed and no other addon has it as a dependency.

David.

PS. Great work guys on the plugin. But I need to disable it from time to time until it's ready for mainstream.

**Comment by MikeInnes** [comment]
Basically, Atom doesn't handle plugin dependencies at all, which is why uber-juno exists. It's not much more than an install script that does a little config and gets the real setup going in Julia. It's therefore a bit hard to know what uninstallation means in that context. Uninstalling or disabling uber-juno itself certainly doesn't (and couldn't) do anything since it's a one-shot thing.

I think the better option is to make sure that the Juno plugins aren't causing issues if you're not using them. Why do you feel the need to disable it? As far as the tool bar itself is concerned it's easy to hide it with the toggle command, or you can remove Julia's icons from the julia-client settings, or you can remove tool-bar completely without any issues.

**Comment by daveh19** [comment]
Hi Mike,

That's a shame but it's a fair response. I should probably file an issue with Atom on that then! ;)

I actually hadn't figured out how to hide the toolbar when I wrote the original issue (maybe I was pressing the wrong key, or some similar stupidity). I'm not really trying to get rid of Juno from my machine, but it was taking up too much screen real estate when I couldn't hide it. I have (mathematical) use cases where I'll use Juno a lot, but for most of my programming I certainly don't want it to be 'present'. But now that I know how to hide it I have no real further complaint.

Thanks,
David.

**Comment by snitramodranoel** [comment]
Hey guys, I'm finally giving up removing any traces of Julia on my computer--I will just completely uninstall Atom and do all the pre-Julia setup again.

**Comment by abcsds** [comment]
Hi guys, have you maybe thought about a "Toggle Juno" button or command (not just the toolbar, but the plugins being used by Juno)?. I use Atom for many things, and cannot have a full IDE open any time I need to change a small config file or edit LaTeX. What do you think? Do I sound capricious by wanting atom without juno by default?
